version: '2.3'

services:
  ci:
    build: ci
    image: $REG/ci/$SRV:$CI    
    volumes:      
      - ./src:/srv
    env_file:
      - ./.env
    labels:
      # - traefik.enable=true
      # - traefik.frontend.rule=PathPrefixStrip:/api/$SRV/
      traefik.enable: "true"
      traefik.http.routers.py-srv-0.rule: PathPrefix(`/py-srv`)
      traefik.http.routers.py-srv-0.middlewares: py-srv-stripprefix
      traefik.http.middlewares.py-srv-stripprefix.stripprefix.prefixes: /py-srv
    
  rt:
    build:
      context: .
      args:
        CI: $REG/ci/$SRV:$CI
    image: $REG/rt/$SRV:$RT    
    env_file:
      - ./.env
    labels:
      traefik.enable: "true"
      traefik.http.routers.py-srv-0.rule: PathPrefix(`/py-srv`)
      traefik.http.routers.py-srv-0.middlewares: py-srv-stripprefix
      traefik.http.middlewares.py-srv-stripprefix.stripprefix.prefixes: /py-srv
    restart: always
    
networks:
  default:
    external:
      name: rt_default