logging:
  log_format: '%(asctime)s - %(levelname)s - %(message)s'
  log_name: 'srv'
  json_log_path: /var/log/srv/srvlog.json
bind_host: 0.0.0.0
bind_port: 80
sub_options1:
  sub_param1: 'text-1'
  sub_param2: 0
  sub_param3: true
sub_options2:
  sub_param1: 'text-2'
  sub_param2: 1
  sub_param3: false